# Input necessary package

In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Input data

In [3]:
data = pd.read_csv("D:\Download\TONGDUN_FEAT_STATIC.csv")

C:\Users\Arif\Anaconda3\envs\ds_env\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (97,98) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

# Metadata definition

In [21]:
col_idex = 'SKP_CREDIT_CASE'
col_obs = 'FPD30_OBS'
col_target = 'FPD30_CNT'
col_time = 'DATE_DECISION'
col_month = 'MONTH'
col_day = 'DAY'
col_index = 'SKP_CREDIT_CASE'

In [11]:
data['DATE_DECISION'] = pd.to_datetime(data['DATE_DECISION'], format='%Y-%m-%d')

In [19]:
data[col_month] = data[col_time].dt.strftime('%Y%m').astype('int')
data[col_day] = data[col_time].dt.strftime('%Y%m%d').astype('int')

In [20]:
data.head()

,SKP_CREDIT_CASE,TONGDUN_ID,USER_ID_GOJEK,USER_ID_GRAB,USER_ID_TOKOPEDIA,TONGDUN_SENT_DTIME,SKP_CREDIT_CASE.1,SKP_CLIENT,PHONE,DATE_DECISION,...,FG_BIN_TRUEIP,FG_BIN_WIFIIP,FG_BIN_GPS,FG_VPNNETMASK,FG_WIFINETMASK,HAS_GOJEK,HAS_GRAB,HAS_TOKOPEDIA,MONTH,DAY
0,73517784,c053415b-657a-496f-b149-692763836548,8.387182e+10,NaN,NaN,2019-04-18 17:13:37.087,73517784,93307,83871822935,2019-04-01,...,1,0,0,NaN,0.0.0.0,1,0,0,201904,20190401
1,73524496,8c08b7f6-cb30-44ad-a601-804b23d8e192,NaN,NaN,NaN,2019-04-30 21:00:40.305,73524496,15288762,85374287304,2019-04-01,...,1,0,0,NaN,0.0.0.0,0,0,0,201904,20190401
2,73573320,64fae998-fbaa-4549-b0b4-a74d11b62b7d,NaN,NaN,NaN,2019-04-26 00:03:29.234,73573320,13137449,89651866534,2019-04-02,...,1,0,1,NaN,0.0.0.0,0,0,0,201904,20190402
3,73577867,e6fd1485-49f7-45d0-a454-5559ec954022,NaN,NaN,NaN,2019-06-08 05:08:46.731,73577867,11681783,81236681467,2019-04-02,...,1,0,0,NaN,0.0.0.0,0,0,0,201904,20190402
4,73626163,92133139-40d8-4961-949b-c17fd04f201e,NaN,NaN,NaN,2019-06-30 12:37:25.607,73626163,22364723,85716083074,2019-04-03,...,1,1,0,NaN,0.0.0.0,0,0,0,201904,20190403

In [8]:
for i in data.columns:
    print(f'{i}: {data[i].dtypes}')

SKP_CREDIT_CASE: int64
TONGDUN_ID: object
USER_ID_GOJEK: float64
USER_ID_GRAB: float64
USER_ID_TOKOPEDIA: float64
TONGDUN_SENT_DTIME: object
SKP_CREDIT_CASE.1: int64
SKP_CLIENT: int64
PHONE: int64
DATE_DECISION: object
MON_DEC: object
CODE_CLIENT_TYPE: object
CODE_PRODUCT_PROFILE: object
NAME_CREDIT_STATUS_APP: object
AMT_CREDIT_TOTAL: float64
TICKET: object
CNT_INSTALMENT: int64
TENURE: object
FPD10_CNT: int64
FPD10_OBS: int64
FPD30_CNT: int64
FPD30_OBS: int64
TOP_AVG_TRANSC_TOTAL: float64
TOP_AVG_TRANSC_SHIPPING: float64
TOP_AVG_TRANSC_INSURANCE: float64
TOP_MAX_TRANSC_SHIPPING: float64
TOP_MAX_TRANSC_INSURANCE: float64
TOP_MAX_TRANSC_TOTAL: float64
TOP_TOTAL_USE_INSURANCE: float64
TOP_SALDO: float64
TOP_TOKOCASH: float64
TOP_TOTAL_BUY_GOLDSTORE: float64
TOP_TOTAL_BUY_OFFCSTORE: float64
TOP_TOTAL_CART_HANDPHONE: float64
TOP_TOTAL_CART_ELECTRIC: float64
TOP_TOTAL_CART_COMPUTER: float64
TOP_TOTAL_CART_ITEMS: float64
TOP_AVG_WISHPROD_PRICE: float64
TOP_MAX_WISHPROD_PRICE: float64
TOP_TOTAL_WISHPROD: float64
GRAB_AVG_DISTANCE: float64
GRAB_MAX_DISTANCE: float64
GRAB_AVG_ORDERFEE: float64
GRAB_MAX_ORDERFEE: float64
GRAB_PAY_CASH: float64
GRAB_PAY_OVO: float64
GRAB_USE_CAR: float64
GRAB_USE_BIKE: float64
GO_AVG_PAY: float64
GO_AVG_POINTS: float64
GO_AVG_DIST: float64
GO_AVG_ORDERFEE: float64
GO_AVG_OTHER_DELFEE: float64
GO_AVG_OTHER_ORDERFEE: float64
GO_AVG_MONEY: float64
GO_MAX_PAY: float64
GO_MAX_POINTS: float64
GO_MAX_DIST: float64
GO_MAX_ORDERFEE: float64
GO_MAX_OTHER_DELFEE: float64
GO_MAX_OTHER_ORDERFEE: float64
GO_MAX_MONEY: float64
GO_FOOD_TOT: float64
GO_RIDE_TOT: float64
GO_CAR_TOT: float64
GO_BLBIRD_TOT: float64
GO_PULSA_TOT: float64
GO_PAY_TOT: float64
GO_SEND_TOT: float64
GO_MASSAGE_TOT: float64
GO_CLEAN_TOT: float64
GO_USING_TOT: float64
GO_FOOD_MONEY: float64
GO_RIDE_MONEY: float64
GO_CAR_MONEY: float64
GO_BLBIRD_MONEY: float64
GO_PULSA_MONEY: float64
GO_PAY_MONEY: float64
GO_SEND_MONEY: float64
GO_MASSAGE_MONEY: float64
GO_CLEAN_MONEY: float64
FG_FINAL_SCORE: float64
FG_FINAL_DECISION: object
FG_ALLOWMOCKLOCATION: object
FG_APPOS: object
FG_AVAILABLEMEMORY: float64
FG_AVAILABLESTORAGE: float64
FG_BIN_BASEBANDVERSION: int64
FG_BATTERYLEVEL: float64
FG_BATTERYSTATUS: object
FG_BATTERYTEMP: float64
FG_BLUEMAC: object
FG_BRAND: object
FG_COUNTRYISO: object
FG_CPUFREQUENCY: float64
FG_CPUHARDWARE: object
FG_CPUTYPE: object
FG_DEVICESVN: object
FG_EVN: object
FG_FREESPACE: float64
FG_HARDWARE: object
FG_BIN_HOST: int64
FG_MAC: object
FG_MCC: float64
FG_MEMORY: float64
FG_MNC: float64
FG_NETWORKTYPE: object
FG_RELEASEVERSION: object
FG_ROOT: object
FG_SCREENRES: object
FG_TOTALMEMORY: float64
FG_TOTALSTORAGE: float64
FG_PROXYINFO: object
FG_OS: object
FG_BRIGHTNESS: float64
FG_VPNIP: object
FG_BIN_CELLIP: int64
FG_BIN_TRUEIP: int64
FG_BIN_WIFIIP: int64
FG_BIN_GPS: int64
FG_VPNNETMASK: object
FG_WIFINETMASK: object
HAS_GOJEK: int64
HAS_GRAB: int64
HAS_TOKOPEDIA: int64

In [23]:
print(f"Data before duplicates are removed: {data.shape}")
data.index = data[col_index]
data = data.drop_duplicates(subset=col_index)
print(f"data after duplicates are removed: {data.shape}")

Data before duplicates are removed: (606959, 127)
data after duplicates are removed: (606959, 127)

In [24]:
data

,SKP_CREDIT_CASE,TONGDUN_ID,USER_ID_GOJEK,USER_ID_GRAB,USER_ID_TOKOPEDIA,TONGDUN_SENT_DTIME,SKP_CREDIT_CASE.1,SKP_CLIENT,PHONE,DATE_DECISION,...,FG_BIN_TRUEIP,FG_BIN_WIFIIP,FG_BIN_GPS,FG_VPNNETMASK,FG_WIFINETMASK,HAS_GOJEK,HAS_GRAB,HAS_TOKOPEDIA,MONTH,DAY
SKP_CREDIT_CASE,,,,,,,,,,,,,,,,,,,,,
73517784,73517784,c053415b-657a-496f-b149-692763836548,8.387182e+10,NaN,NaN,2019-04-18 17:13:37.087,73517784,93307,83871822935,2019-04-01,...,1,0,0,NaN,0.0.0.0,1,0,0,201904,20190401
73524496,73524496,8c08b7f6-cb30-44ad-a601-804b23d8e192,NaN,NaN,NaN,2019-04-30 21:00:40.305,73524496,15288762,85374287304,2019-04-01,...,1,0,0,NaN,0.0.0.0,0,0,0,201904,20190401
73573320,73573320,64fae998-fbaa-4549-b0b4-a74d11b62b7d,NaN,NaN,NaN,2019-04-26 00:03:29.234,73573320,13137449,89651866534,2019-04-02,...,1,0,1,NaN,0.0.0.0,0,0,0,201904,20190402
73577867,73577867,e6fd1485-49f7-45d0-a454-5559ec954022,NaN,NaN,NaN,2019-06-08 05:08:46.731,73577867,11681783,81236681467,2019-04-02,...,1,0,0,NaN,0.0.0.0,0,0,0,201904,20190402
73626163,73626163,92133139-40d8-4961-949b-c17fd04f201e,NaN,NaN,NaN,2019-06-30 12:37:25.607,73626163,22364723,85716083074,2019-04-03,...,1,1,0,NaN,0.0.0.0,0,0,0,201904,20190403
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87439245,87439245,d2e31607-053c-48ed-af0d-8ec55e742e7e,NaN,NaN,NaN,2019-06-25 19:19:57.997,87439245,24187139,82284400077,2019-06-25,...,1,0,1,NaN,0.0.0.0,0,0,0,201906,20190625
87439407,87439407,c3e5c947-1020-46ce-ab2b-5969d3300c6e,NaN,NaN,NaN,2019-06-25 12:15:40.745,87439407,24190907,82385683326,2019-06-25,...,1,1,0,NaN,255.255.255.0,0,0,0,201906,20190625
87440158,87440158,def70501-bd84-48bf-88df-6f78f31738d9,NaN,NaN,NaN,2019-06-25 15:29:40.667,87440158,24182012,82213541533,2019-06-25,...,1,0,0,NaN,0.0.0.0,0,0,0,201906,20190625
87440697,87440697,3ffd4657-c07c-4f37-a925-32ba5272ae61,NaN,NaN,NaN,2019-06-26 12:39:03.489,87440697,24190614,82138398502,2019-06-25,...,1,0,0,NaN,0.0.0.0,0,0,0,201906,20190625
87440794,87440794,1dd1d3cb-af38-481b-8fae-230a9ca5b578,NaN,NaN,NaN,2019-06-25 19:52:57.271,87440794,10845281,81904328890,2019-06-25,...,1,0,1,NaN,0.0.0.0,0,0,0,201906,20190625